[build]
    publish ="dist"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src self https://app.netlify.com/; script-src-elem self https://app.netlify.com/; style-src-elem self https://app.netlify.com/; object-src none; frame-ancestors none"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
